### ISSUE TITLE
UnicodeDecodeError: 'utf-8' ocdec can't decode byte 0x96 in position  1283: invalid start byte

### ISSUE THREAD

**Issue by metaperl** [oracle/python-oracledb#66] opened 2022-09-23 12:18 UTC
1. What versions are you using?

2. Is it an error or a hang or a crash?

`error`

4. What error(s) or behavior you are seeing?

```
UnicodeDecodeError: 'utf-8' ocdec can't decode byte 0x96 in position  1283: invalid start byte
```

5. Does your application call init_oracle_client()?

no. im in thin mode.

7. Include a runnable Python script that shows the problem.

i do not have company permission to do so.

**Comment by metaperl** [comment] 2022-09-23 12:21
all of the things that i entered got lost;

i'm on Windows 10
`sys.maxsize` is greater than `2**32`
python version is 3.8.3
oracledb version is 1.1.0

**Comment by metaperl** [comment] 2022-09-23 12:22
Do note that this is not a new issue. it existed in cx_Oracle and was never resolved because the people reporting never provided reproduceable test cases. And that also includes me at the moment unless i can obtain permission to create one.

here are the former cx-oracle issues related to this;
* https://github.com/oracle/python-cx_Oracle/issues/573
* https://github.com/oracle/python-cx_Oracle/issues/540

**Comment by anthony-tuininga** [comment] 2022-09-23 13:28
If you are unable to provide us with any information to help you resolve the issue, how do you expect us to help you?!?

The [documentation](https://python-oracledb.readthedocs.io/en/latest/user_guide/sql_execution.html#querying-corrupt-data) surrounding querying corrupt data may be relevant -- if so, this is not a bug. Do you get the same results using thick mode?

**Comment by venkatesan001** [comment] 2022-09-25 22:06
@anthony-tuininga 

I am also getting the UnicodeDecodeError in python-oracledb. We are upgrading our package from cx_Oracle to python-oracledb. We are not getting this error while using the cx_Oracle but it's in python-oracledb.
**cx_oracle connection:**
`Connection = cx_oracle.connect (user=USERNAME, password=PASSWORD, dsn = DSN, encoding=UTF-16, encoding=UTF-16)`
**Python-oracledb connection:**
`Connection = Python-oracledb.connect (user=USERNAME, password=PASSWORD, dsn = DSN,  encoding=UTF-16, encoding=UTF-16)`
**Error Message:**
(UnicodeDecodeError('utf-8', b'REPAIRING THE WORLD\x92S ESTUARIES', 19, 20, 'invalid start byte'),)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x92 in position 19: invalid start byte
**Database:** 19c
**NLS_NCHAR_CHARACTERSET** = AL16UTF16 ( SELECT value AS db_ncharset FROM nls_database_parameters WHERE parameter = 'NLS_NCHAR_CHARACTERSET')

Please let me know if there is anything I am missing in the Python-Oracledb connection.

**Comment by venkatesan001** [comment] 2022-09-27 16:16
Any update on this please?

**Comment by anthony-tuininga** [comment] 2022-09-27 19:15
Can you run the following query?

```sql
    SELECT value AS db_charset
    FROM nls_database_parameters
    WHERE parameter = 'NLS_CHARACTERSET';
```

Can you also do the following in a command line?

set NLS_LANG=.AL32UTF8
sqlplus USERNAME/PASSWORD@DSN

Then, in SQL*Plus perform the same query that you are having difficulty with using python-oracledb.

Since python-oracledb now uses UTF-8 as the encoding when talking to the database it is critical that the database character set actually match the data in the database (so the database can perform any conversions necessary). It is possible to set NLS_LANG to match the database character set -- and then send data in any encoding to the database and it will accept it. But doing so means that you have to always set NLS_LANG to that value and always process the data in the same way or you will get encode/decode errors like the one you are experiencing.

Based on the data you provided, I suspect that you are actually storing data in the database in encoding "WINDOWS-1252" where 0x92 is a "fancy" quote. If that is indeed the case, you will need to correct your data!

**Comment by anthony-tuininga** [comment] 2022-09-27 19:18
You can use the technique noted in the [documentation](https://python-oracledb.readthedocs.io/en/latest/user_guide/sql_execution.html#fetching-raw-data) to bypass the decode stage and get the raw data. You can then decode it yourself using the "real" encoding -- as a temporary workaround until the data in the database can be fixed, of course!

**Comment by cjbj** [comment] 2022-09-27 22:45
> Connection = Python-oracledb.connect (user=USERNAME, password=PASSWORD, dsn = DSN, nencoding=UTF-16, encoding=UTF-16)

For completeness, the `encoding` and `nencoding` parameters are ignored in python-oracledb (and can be removed) because the driver uses UTF-8 as mentioned by @anthony-tuininga.

**Comment by metaperl** [comment] 2022-10-03 16:55
> Can you run the following query?

    SELECT value AS db_charset
    FROM nls_database_parameters
    WHERE parameter = 'NLS_CHARACTERSET';

this returns `AL32UTF8`

    SELECT value AS db_charset
    FROM nls_database_parameters
    WHERE parameter = 'NLS_NCHAR_CHARACTERSET';

this returns `AL16UTF16`

    SELECT DISTINCT client_charset AS client_charset
    FROM v$session_connect_info
    WHERE sid = SYS_CONTEXT('USERENV', 'SID');

this returns `AL32UTF8`

**Comment by anthony-tuininga** [comment] 2022-10-03 16:59
Thanks. I think that clinches the fact that you have corrupted data in the database. See my earlier comment about a workaround -- but I would suggest that you correct the data if at all possible!

**Comment by cjbj** [comment] 2022-10-27 03:11
Closing - no update

**Closed by cjbj** 2022-10-27 03:11 UTC
Labels: question
