### ISSUE TITLE
SSL authentication not working for Amazon RDS (using thin model)

### ISSUE THREAD

**Issue by moxarth-elastic** [oracle/python-oracledb#139] opened 2023-02-09 08:33 UTC
1. What versions are you using?

Give your database version.

Also run Python and show the output of:

    import sys
    import platform

    print("platform.platform:", platform.platform())
    print("sys.maxsize > 2**32:", sys.maxsize > 2**32)
    print("platform.python_version:", platform.python_version())

And:

    import oracledb
    print("oracledb.__version__:", oracledb.__version__)

Oracledb Version: `1.2.2`
Database Version: `Oracle Database 19c Standard Edition 2 (Amazon RDS )`

Output of first code:
```
platform.platform: Linux-5.15.0-57-generic-x86_64-with-glibc2.35
sys.maxsize > 2**32: True
platform.python_version: 3.10.6
```
Output of second code:
```
oracledb.__version__: 1.2.2
```

2. Is it an error or a hang or a crash?
`Error`

3. What error(s) or behavior you are seeing?

`oracledb.exceptions.OperationalError: DPY-6005: cannot connect to database. Connection failed with "[SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:997)"`

4. Does your application call init_oracle_client()?
No, I am using thin model

5. Include a runnable Python script that shows the problem.
```
import oracledb

wall_loc = "path-to-wallet"

kwargs = {
    "wallet_location": wall_loc,
}

with oracledb.connect(
    user=username,
    password=password,
    dsn=dsn,
    **kwargs,
) as ocon:
    with ocon.cursor() as cursor:
        sql = """select '['||systimestamp||'] Connectivity OK' from dual"""
        for r in cursor.execute(sql):
            print(r[0])

```

I am trying to authenticate my amazon oracle rds service with SSL connection using a thin model. Currently, I am pasting rds-ca-2019-root.pem in ewallet.pem and passing the path in wallet_location without a password. but it throws oracledb.exceptions.OperationalError: DPY-6005: cannot connect to database. Connection failed with "[SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure

In DSN i am using TCPS protocol and ssl port.

**Comment by cjbj** [comment] 2023-02-20 04:09
Duplicate of https://github.com/oracle/python-oracledb/discussions/138

**Closed by cjbj** 2023-02-20 04:09 UTC
Labels: help wanted
