### ISSUE TITLE
Installing in a virtual env wrecks system wide ssl certification for python

### ISSUE THREAD

**Issue by icfly2** [oracle/python-oracledb#193] opened 2023-06-16 12:17 UTC
1. What versions are you using?

Tried installing latest

Give your database version.

Also run Python and show the output of:

```
>>> import sys
>>> import platform
rm:", platform.platform())
print("sys.maxsize > 2*>>> 
>>> print("platform.platform:", platform.platform())
platform.platform: Linux-5.15.90.1-microsoft-standard-WSL2-x86_64-with-glibc2.31
>>> print("sys.maxsize > 2**32:", sys.maxsize > 2**32)
sys.maxsize > 2**32: True
>>> print("platform.python_version:", platform.python_version())
platform.python_version: 3.10.8
```

And:

import oracledb
print("oracledb.__version__:", oracledb.__version__)
oracledb.__version__: 1.3.2

2. Is it an error or a hang or a crash?
3. Instalation error

4. What error(s) or behavior you are seeing?

```
(env) rum@rum-avd:~/asap2_admin$ python -m pip install oracledb --upgrade
Defaulting to user installation because normal site-packages is not writeable
Looking in indexes: https://pypi.org/simple
Collecting oracledb
  Downloading ***/28ebd5ed-b704-4485-9dd7-0b6f0c6c6ff2/pypi/download/oracledb/1.3.2/oracledb-1.3.2-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (7.6 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 7.6/7.6 MB 17.2 MB/s eta 0:00:00
Collecting cryptography>=3.2.1 (from oracledb)
  Downloading ***/28ebd5ed-b704-4485-9dd7-0b6f0c6c6ff2/pypi/download/cryptography/41.0.1/cryptography-41.0.1-cp37-abi3-manylinux_2_28_x86_64.whl (4.3 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.3/4.3 MB 16.2 MB/s eta 0:00:00
Requirement already satisfied: cffi>=1.12 in /home/rum/.local/lib/python3.10/site-packages (from cryptography>=3.2.1->oracledb) (1.15.1)
Requirement already satisfied: pycparser in /home/rum/.local/lib/python3.10/site-packages (from cffi>=1.12->cryptography>=3.2.1->oracledb) (2.21)
Installing collected packages: cryptography, oracledb
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
launchpadlib 1.10.13 requires testresources, which is not installed.
msal 1.21.0 requires cryptography<41,>=0.6, but you have cryptography 41.0.1 which is incompatible.
Successfully installed cryptography-41.0.1 oracledb-1.3.2

rum@rum-avd:~/asap2_admin$ python
Python 3.10.8 (main, Oct 12 2022, 19:14:26) [GCC 9.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from aa_service_utils.database.connections import DBConnection
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/rum/.local/lib/python3.10/site-packages/aa_service_utils/database/connections.py", line 12, in <module>
    from aa_service_utils.database.databricks import create_databricks_connection
  File "/home/rum/.local/lib/python3.10/site-packages/aa_service_utils/database/databricks.py", line 4, in <module>
    from databricks.sql.client import Connection
  File "/home/rum/.local/lib/python3.10/site-packages/databricks/sql/client.py", line 5, in <module>
    import requests
  File "/usr/lib/python3/dist-packages/requests/__init__.py", line 95, in <module>
    from urllib3.contrib import pyopenssl
  File "/usr/lib/python3/dist-packages/urllib3/contrib/pyopenssl.py", line 46, in <module>
    import OpenSSL.SSL
  File "/usr/lib/python3/dist-packages/OpenSSL/__init__.py", line 8, in <module>
    from OpenSSL import crypto, SSL
  File "/usr/lib/python3/dist-packages/OpenSSL/crypto.py", line 1553, in <module>
    class X509StoreFlags(object):
  File "/usr/lib/python3/dist-packages/OpenSSL/crypto.py", line 1573, in X509StoreFlags
    CB_ISSUER_CHECK = _lib.X509_V_FLAG_CB_ISSUER_CHECK
AttributeError: module 'lib' has no attribute 'X509_V_FLAG_CB_ISSUER_CHECK'
>>> exit()
(env) rum@rum-avd:~/asap2_admin$ pip install pyopenssl --upgrade
Traceback (most recent call last):
  File "/home/rum/asap2_admin/env/bin/pip", line 5, in <module>
    from pip._internal.cli.main import main
ModuleNotFoundError: No module named 'pip'
(env) rum@rum-avd:~/asap2_admin$ sudo  docker-compose -f test-docker-compose.yml build admin 
Traceback (most recent call last):
  File "/usr/bin/docker-compose", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 3254, in <module>
    def _initialize_master_working_set():
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 3237, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 3266, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 584, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 901, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 787, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'backports.ssl_match_hostname<4,>=3.5' distribution was not found and is required by docker-compose
(env) rum@rum-avd:~/asap2_admin$ deactivate
rum@rum-avd:~/asap2_admin$ sudo  docker-compose -f test-docker-compose.yml build admin 
Traceback (most recent call last):
  File "/usr/bin/docker-compose", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 3254, in <module>
    def _initialize_master_working_set():
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 3237, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 3266, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 584, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 901, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 787, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'backports.ssl_match_hostname<4,>=3.5' distribution was not found and is required by docker-compose
```

**Comment by cjbj** [comment] 2023-06-16 23:54
python-oracledb needs the cryptopgraphy package.  Are you seeing some side effect of the cryptography package installation?  Try installing just that package and not python-oracledb and see whether you have the same issue.

**Comment by cjbj** [comment] 2023-07-03 05:26
@icfly2 did you confirm the issue is the cryptography package?

**Comment by anthony-tuininga** [comment] 2023-07-26 20:42
Note these issues reported in your installation log:

```
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
launchpadlib 1.10.13 requires testresources, which is not installed.
msal 1.21.0 requires cryptography<41,>=0.6, but you have cryptography 41.0.1 which is incompatible.
```

Based on this I don't think this is an issue with python-oracledb and will close this issue. If you disagree, please feel free to re-open with an explanation. Thanks!

**Closed by anthony-tuininga** 2023-07-26 20:42 UTC
Labels: install & configuration
